'use client'

import { useEffect, useMemo, useState } from 'react'
import { useRouter } from 'next/navigation'
import MemberShell from '../../../components/MemberShell'
import { supabase } from '../../../lib/supabase'

type Affiliate = {id:string; referral_code:string; status:string; display_name:string|null; payout_method:string|null; payout_account_name:string|null; payout_account_number:string|null}
type Settings = {enabled:boolean; default_commission_percent:number; minimum_payout:number; auto_approve_affiliate:boolean; cookie_duration_days:number}
type Rule = {product_id:string; affiliate_enabled:boolean; commission_percent:number|null; products?:{name?:string;slug?:string;price?:number}|null}
type Commission = {id:string; commission_amount:number; commission_percent:number; status:string; created_at:string; products?:{name?:string}|null}

const money=(n:number)=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(Number(n||0))

export default function AffiliateCenter(){
 const router=useRouter(); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState(false); const [msg,setMsg]=useState('')
 const [email,setEmail]=useState(''); const [name,setName]=useState(''); const [settings,setSettings]=useState<Settings|null>(null); const [aff,setAff]=useState<Affiliate|null>(null)
 const [clicks,setClicks]=useState(0); const [orders,setOrders]=useState(0); const [comm,setComm]=useState<Commission[]>([])
 const [productQuery,setProductQuery]=useState(''); const [productResults,setProductResults]=useState<Rule[]>([]); const [searchingProducts,setSearchingProducts]=useState(false); const [selectedProduct,setSelectedProduct]=useState<Rule|null>(null)
 const [payout,setPayout]=useState({display_name:'',payout_method:'',account_name:'',account_number:''})
 async function load(){ setLoading(true); setMsg(''); const {data:{user}}=await supabase.auth.getUser(); if(!user){router.replace('/login');return}; setEmail(user.email||'');
  const {data:profile}=await supabase.from('profiles').select('full_name').eq('id',user.id).maybeSingle(); setName(profile?.full_name||user.email?.split('@')[0]||'Member')
  const {data:st}=await supabase.from('affiliate_settings').select('enabled,default_commission_percent,minimum_payout,auto_approve_affiliate,cookie_duration_days').eq('id',1).maybeSingle(); setSettings(st as Settings|null)
  const {data:a}=await supabase.from('affiliates').select('id,referral_code,status,display_name,payout_method,payout_account_name,payout_account_number').eq('user_id',user.id).maybeSingle(); const aa=a as Affiliate|null; setAff(aa)
  if(aa){ setPayout({display_name:aa.display_name||'',payout_method:aa.payout_method||'',account_name:aa.payout_account_name||'',account_number:aa.payout_account_number||''})
   const [{count:c},{count:o},{data:cm}]=await Promise.all([supabase.from('affiliate_clicks').select('id',{count:'exact',head:true}).eq('affiliate_id',aa.id),supabase.from('affiliate_orders').select('id',{count:'exact',head:true}).eq('affiliate_id',aa.id),supabase.from('affiliate_commissions').select('id,commission_amount,commission_percent,status,created_at,products(name)').eq('affiliate_id',aa.id).order('created_at',{ascending:false}).limit(20)]); setClicks(c||0);setOrders(o||0);setComm((cm||[]) as unknown as Commission[])
  }
  setLoading(false)
 }
 useEffect(()=>{load()},[])
 const sums=useMemo(()=>comm.reduce((a,c)=>{a[c.status]=(a[c.status]||0)+Number(c.commission_amount||0);return a},{pending:0,approved:0,paid:0} as Record<string,number>),[comm])
 async function join(){setBusy(true);setMsg('');const {error}=await supabase.rpc('join_affiliate_program');setBusy(false);if(error)setMsg(error.message);else{setMsg('Pendaftaran affiliate berhasil.');load()}}
 async function savePayout(){setBusy(true);setMsg('');const {error}=await supabase.rpc('update_affiliate_payout_profile',{p_display_name:payout.display_name,p_payout_method:payout.payout_method,p_account_name:payout.account_name,p_account_number:payout.account_number});setBusy(false);setMsg(error?error.message:'Data payout berhasil disimpan.');if(!error)load()}
 async function searchProducts(){ const q=productQuery.trim(); setSelectedProduct(null); if(q.length<2){setProductResults([]);setMsg('Ketik minimal 2 karakter untuk mencari produk.');return} setSearchingProducts(true);setMsg(''); const safe=q.replace(/[,%()]/g,' ').trim(); const {data,error}=await supabase.from('product_affiliate_rules').select('product_id,affiliate_enabled,commission_percent,products!inner(name,slug,price,status)').eq('affiliate_enabled',true).eq('products.status','published').or(`name.ilike.%${safe}%,slug.ilike.%${safe}%`,{referencedTable:'products'}).limit(10); setSearchingProducts(false); if(error){setProductResults([]);setMsg(error.message);return}; setProductResults((data||[]) as unknown as Rule[]) }
 function link(slug?:string){if(typeof window==='undefined'||!aff)return '';return `${window.location.origin}${slug?`/product/${slug}`:'/'}?ref=${encodeURIComponent(aff.referral_code)}`}
 async function copy(v:string){await navigator.clipboard.writeText(v);setMsg('Link affiliate berhasil disalin.')}
 return <MemberShell email={email} displayName={name} active="affiliate"><div className="af-wrap">
  <div className="af-head"><div><span>AFFILIATE CENTER</span><h1>Affiliate Saya</h1><p>Promosikan produk yang diizinkan dan pantau komisi Anda.</p></div><button onClick={load}>↻ Refresh</button></div>
  {msg&&<div className="af-note">{msg}</div>}
  {loading?<div className="af-card">Memuat Affiliate Center...</div>:!settings?.enabled?<div className="af-card af-empty"><h2>Program Affiliate Belum Aktif</h2><p>Super Admin belum mengaktifkan program affiliate. Setelah diaktifkan, member dapat mendaftar dari halaman ini.</p></div>:!aff?<div className="af-card af-empty"><h2>Gabung Program Affiliate</h2><p>Komisi default {Number(settings.default_commission_percent)}% · Cookie {settings.cookie_duration_days} hari · {settings.auto_approve_affiliate?'Aktif otomatis setelah daftar':'Memerlukan persetujuan admin'}.</p><button className="primary" disabled={busy} onClick={join}>{busy?'Memproses...':'Daftar Jadi Affiliate'}</button></div>:<>
   <div className="af-grid stats"><div className="af-card"><small>STATUS</small><b className={`status ${aff.status}`}>{aff.status.toUpperCase()}</b><p>Kode: <strong>{aff.referral_code}</strong></p></div><div className="af-card"><small>REFERRAL CLICKS</small><h2>{clicks}</h2><p>Total klik tercatat</p></div><div className="af-card"><small>REFERRED ORDERS</small><h2>{orders}</h2><p>Order teratribusi</p></div><div className="af-card"><small>KOMISI TERSEDIA</small><h2>{money(sums.approved||0)}</h2><p>Pending {money(sums.pending||0)}</p></div></div>
   {aff.status==='active'?<><div className="af-card"><div className="af-title"><div><small>REFERRAL LINK</small><h2>Link Affiliate Utama</h2></div></div><div className="copy"><input readOnly value={link()}/><button onClick={()=>copy(link())}>Copy Link</button></div></div>
   <div className="af-grid two"><div className="af-card"><small>AFFILIATE LINK GENERATOR</small><h2>Cari Produk & Generate Link</h2><p>Cari produk yang ingin dipromosikan. Hanya produk published dengan affiliate aktif yang ditampilkan.</p><div className="product-search"><input value={productQuery} onChange={e=>setProductQuery(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')searchProducts()}} placeholder="Cari nama atau slug produk..."/><button onClick={searchProducts} disabled={searchingProducts}>{searchingProducts?'Mencari...':'Cari Produk'}</button></div>{productResults.length>0&&<div className="list">{productResults.map(r=><div className="row" key={r.product_id}><div><strong>{r.products?.name||'Produk'}</strong><span>{money(Number(r.products?.price||0))} · Komisi {r.commission_percent??settings.default_commission_percent}%</span></div><button onClick={()=>setSelectedProduct(r)}>Pilih</button></div>)}</div>}{selectedProduct&&<div className="generated"><small>LINK AFFILIATE PRODUK</small><strong>{selectedProduct.products?.name||'Produk'}</strong><div className="copy"><input readOnly value={link(selectedProduct.products?.slug)}/><button onClick={()=>copy(link(selectedProduct.products?.slug))}>Copy Link</button></div><a href={link(selectedProduct.products?.slug)} target="_blank" rel="noreferrer">Buka Produk ↗</a></div>}</div>
   <div className="af-card"><small>PAYOUT PROFILE</small><h2>Rekening Pencairan</h2><div className="form"><input placeholder="Nama affiliate" value={payout.display_name} onChange={e=>setPayout({...payout,display_name:e.target.value})}/><input placeholder="Metode: BCA / DANA / dll" value={payout.payout_method} onChange={e=>setPayout({...payout,payout_method:e.target.value})}/><input placeholder="Nama pemilik rekening" value={payout.account_name} onChange={e=>setPayout({...payout,account_name:e.target.value})}/><input placeholder="Nomor rekening / akun" value={payout.account_number} onChange={e=>setPayout({...payout,account_number:e.target.value})}/><button className="primary" disabled={busy} onClick={savePayout}>Simpan Payout</button></div></div></div>
   <div className="af-card"><small>RIWAYAT KOMISI</small><h2>Komisi Terbaru</h2>{comm.length===0?<p>Belum ada komisi.</p>:<div className="table"><div className="tr th"><span>Produk</span><span>Komisi</span><span>Status</span><span>Tanggal</span></div>{comm.map(c=><div className="tr" key={c.id}><span>{c.products?.name||'Produk'}</span><span>{money(c.commission_amount)} ({Number(c.commission_percent)}%)</span><span>{c.status}</span><span>{new Date(c.created_at).toLocaleDateString('id-ID')}</span></div>)}</div>}</div></>:<div className="af-card af-empty"><h2>Status Affiliate: {aff.status}</h2><p>{aff.status==='pending'?'Pendaftaran Anda menunggu persetujuan admin.':'Akun affiliate belum dapat digunakan untuk promosi.'}</p></div>}
  </>}
 </div><style jsx>{`.af-wrap{max-width:1250px;margin:auto}.af-head{display:flex;justify-content:space-between;gap:20px;align-items:flex-start;margin-bottom:18px}.af-head span,.af-card small{font-size:11px;font-weight:900;letter-spacing:1.2px;color:#6366f1}.af-head h1{margin:5px 0 4px;font-size:30px}.af-head p,.af-card p{color:#64748b}.af-head button,.row button,.copy button{border:1px solid #dbe3f0;background:#fff;border-radius:11px;padding:10px 14px;font-weight:800;cursor:pointer}.af-grid{display:grid;gap:14px}.stats{grid-template-columns:repeat(4,1fr);margin-bottom:14px}.two{grid-template-columns:1.2fr .8fr;margin:14px 0}.af-card{background:rgba(255,255,255,.9);border:1px solid #e4e8f2;border-radius:18px;padding:20px;box-shadow:0 14px 40px rgba(51,65,85,.06)}.af-card h2{margin:7px 0 10px;font-size:20px}.af-card.stats h2{font-size:25px}.status{display:inline-block;margin:10px 0;padding:6px 10px;border-radius:999px;background:#eef2ff;color:#4338ca}.status.active{background:#dcfce7;color:#15803d}.status.pending{background:#fef3c7;color:#b45309}.af-empty{text-align:center;padding:42px 24px}.primary{border:0;border-radius:11px;padding:11px 16px;background:linear-gradient(135deg,#2563eb,#7c3aed);color:#fff;font-weight:900;cursor:pointer}.copy{display:flex;gap:8px}.copy input,.form input{width:100%;border:1px solid #dbe3f0;border-radius:11px;padding:11px 12px;background:#f8fafc}.form{display:grid;gap:9px}.product-search{display:flex;gap:8px;margin-top:14px}.product-search input{flex:1;border:1px solid #dbe3f0;border-radius:11px;padding:11px 12px;background:#f8fafc}.product-search button{border:0;border-radius:11px;padding:11px 16px;background:linear-gradient(135deg,#2563eb,#7c3aed);color:#fff;font-weight:900;cursor:pointer}.product-search button:disabled{opacity:.6}.generated{margin-top:14px;padding:14px;border:1px solid #dbeafe;background:#f8fbff;border-radius:14px;display:grid;gap:9px}.generated>a{font-size:13px;font-weight:800;color:#4f46e5;text-decoration:none}.list{display:grid;gap:8px;margin-top:14px}.row{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:12px;border:1px solid #edf0f6;border-radius:12px}.row div{display:grid;gap:3px}.row span{font-size:12px;color:#64748b}.table{overflow:auto;margin-top:12px}.tr{min-width:650px;display:grid;grid-template-columns:1.5fr 1fr .7fr .8fr;gap:10px;padding:11px 8px;border-top:1px solid #eef2f7;font-size:13px}.th{font-weight:900;color:#64748b}.af-note{margin-bottom:14px;padding:11px 14px;border-radius:12px;background:#eef6ff;border:1px solid #dbeafe;color:#1e40af}@media(max-width:1050px){.stats{grid-template-columns:repeat(2,1fr)}.two{grid-template-columns:1fr}}@media(max-width:620px){.product-search{display:grid}.stats{grid-template-columns:1fr}.af-head{display:block}.af-head button{margin-top:12px}.copy{display:grid}.af-head h1{font-size:25px}}`}</style></MemberShell>
}
