'use client'

import { useEffect, useMemo, useState } from 'react'
import { useParams, useRouter } from 'next/navigation'
import { supabase } from '../../../../../lib/supabase'

type Mode = 'none' | 'internal' | 'external'
type Product = { id:string; name:string; slug:string; status:string; sales_page_mode?:Mode|null; sales_page_html?:string|null; external_sales_page_url?:string|null }

const starter = `<!doctype html>
<html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Sales Page</title>
<style>body{font-family:Arial,sans-serif;margin:0;background:#f7f8fc;color:#172033}.wrap{max-width:860px;margin:auto;padding:70px 22px;text-align:center}.card{background:white;border:1px solid #e5e7ef;border-radius:24px;padding:48px;box-shadow:0 20px 60px #66708518}h1{font-size:46px;margin:0 0 16px}p{color:#667085;line-height:1.7}.btn{display:inline-block;margin-top:20px;padding:15px 24px;border-radius:12px;background:#5b59f6;color:white;text-decoration:none;font-weight:700}</style></head>
<body><main class="wrap"><section class="card"><h1>{{PRODUCT_NAME}}</h1><p>Tulis copywriting sales page produk Anda di sini.</p><a class="btn" href="{{CHECKOUT_URL}}">Beli Sekarang</a></section></main></body></html>`

export default function ProductSalesPageAdmin(){
  const { id } = useParams<{id:string}>(); const router=useRouter()
  const [product,setProduct]=useState<Product|null>(null); const [mode,setMode]=useState<Mode>('none'); const [html,setHtml]=useState(''); const [external,setExternal]=useState(''); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [msg,setMsg]=useState(''); const [err,setErr]=useState(''); const [tab,setTab]=useState<'editor'|'preview'>('editor')
  useEffect(()=>{ void load() },[id])
  async function load(){ setLoading(true); setErr(''); const {data:{user}}=await supabase.auth.getUser(); if(!user){router.replace('/login');return} const pr=await supabase.from('profiles').select('role,status').eq('id',user.id).maybeSingle(); if(!pr.data || pr.data.status!=='active' || !['admin','super_admin'].includes(pr.data.role)){router.replace('/login');return} const r=await supabase.from('products').select('id,name,slug,status,sales_page_mode,sales_page_html,external_sales_page_url').eq('id',id).maybeSingle(); if(r.error||!r.data){setErr(r.error?.message||'Produk tidak ditemukan.');setLoading(false);return} const p=r.data as Product; setProduct(p); setMode((p.sales_page_mode||'none') as Mode); setHtml(p.sales_page_html||''); setExternal(p.external_sales_page_url||''); setLoading(false) }
  const checkoutPath=product?`/checkout/${product.slug}`:''
  const preview=useMemo(()=>{ if(!product)return ''; return (html||starter).replaceAll('{{PRODUCT_NAME}}',product.name).replaceAll('{{CHECKOUT_URL}}',checkoutPath) },[html,product,checkoutPath])
  async function save(){ if(!product)return; setSaving(true);setErr('');setMsg(''); if(mode==='external'){try{const u=new URL(external);if(!['http:','https:'].includes(u.protocol))throw new Error()}catch{setErr('External URL harus URL http/https yang valid.');setSaving(false);return}} const r=await supabase.rpc('admin_update_product_sales_page',{p_product_id:product.id,p_mode:mode,p_html:html||null,p_external_url:external||null}); if(r.error)setErr(r.error.message); else setMsg('Pengaturan Sales Page berhasil disimpan.'); setSaving(false) }
  function copy(v:string){navigator.clipboard.writeText(v);setMsg('Link berhasil dicopy.')}
  if(loading)return <div className="shell">Memuat...</div>
  return <div className="shell"><div className="top"><button onClick={()=>router.push('/admin/products')}>← Products</button><div><b>iMersSUPA</b><span> SALES PAGE MANAGER</span></div></div><main><div className="hero"><div><small>PRODUCT SALES PAGE</small><h1>{product?.name}</h1><p>Sales page bersifat opsional. Direct Checkout tetap aktif pada semua mode.</p></div><button className="save" disabled={saving} onClick={()=>void save()}>{saving?'Menyimpan...':'Simpan Pengaturan'}</button></div>{err&&<div className="alert err">{err}</div>}{msg&&<div className="alert ok">{msg}</div>}
  <section className="card"><h2>1. Pilih Mode Sales Page</h2><div className="modes">{([['none','Tidak Pakai Sales Page','Gunakan link checkout langsung dari website, WA, bio link atau landing page lain.'],['internal','Internal HTML','Paste atau edit HTML salespage dan tampilkan langsung dari iMersSUPA.'],['external','External URL','Arahkan halaman produk ke salespage yang disimpan di website/platform lain.']] as const).map(x=><label key={x[0]} className={mode===x[0]?'active':''}><input type="radio" checked={mode===x[0]} onChange={()=>setMode(x[0])}/><strong>{x[1]}</strong><span>{x[2]}</span></label>)}</div></section>
  <section className="card"><h2>2. Quick Links</h2><p>Direct Checkout selalu aktif. Link Sales Page mengikuti mode yang dipilih.</p>
    <div className="quick"><div><b>Direct Checkout</b><div className="link"><code>{typeof window!=='undefined'?window.location.origin+checkoutPath:checkoutPath}</code><button onClick={()=>copy(window.location.origin+checkoutPath)}>Copy</button><button onClick={()=>window.open(checkoutPath,'_blank')}>Buka</button></div></div>
    <div><b>Sales Page</b>{mode==='none'?<p className="disabled-link">Tidak digunakan untuk produk ini.</p>:<div className="link"><code>{mode==='internal'?(typeof window!=='undefined'?window.location.origin:`''`)+`/product/${product?.slug}`:external||'Isi External URL terlebih dahulu'}</code>{(mode==='internal'||external)&&<><button onClick={()=>copy(mode==='internal'?window.location.origin+`/product/${product?.slug}`:external)}>Copy</button><button onClick={()=>window.open(mode==='internal'?`/product/${product?.slug}`:external,'_blank')}>Buka</button></>}</div>}</div></div>
  </section>
  {mode==='external'&&<section className="card"><h2>3. External Sales Page</h2><p>Masukkan URL salespage eksternal. Parameter referral/coupon dari link produk akan diteruskan saat redirect.</p><input className="url" value={external} onChange={e=>setExternal(e.target.value)} placeholder="https://websiteanda.com/salespage-produk"/></section>}
  {mode==='internal'&&<section className="card"><div className="tabs"><h2>3. Internal HTML Sales Page</h2><div><button className={tab==='editor'?'sel':''} onClick={()=>setTab('editor')}>HTML Editor</button><button className={tab==='preview'?'sel':''} onClick={()=>setTab('preview')}>Preview</button></div></div><p>Gunakan <code>{'{{PRODUCT_NAME}}'}</code> dan <code>{'{{CHECKOUT_URL}}'}</code>. Checkout URL otomatis mengikuti produk.</p>{tab==='editor'?<><textarea value={html} onChange={e=>setHtml(e.target.value)} placeholder="Paste full HTML di sini..."/><div className="tools"><button onClick={()=>setHtml(starter)}>Pakai Template Default</button><button onClick={()=>setHtml('')}>Kosongkan</button></div></>:<iframe title="Sales page preview" sandbox="allow-forms allow-popups allow-popups-to-escape-sandbox" srcDoc={preview}/>}</section>}
  </main><style jsx global>{`*{box-sizing:border-box}body{margin:0;background:linear-gradient(135deg,#f5f8ff,#fff7fd);font-family:Inter,Arial,sans-serif;color:#18243b}.shell{min-height:100vh}.top{height:68px;background:#ffffffdd;border-bottom:1px solid #e1e5ef;display:flex;align-items:center;justify-content:space-between;padding:0 28px;position:sticky;top:0;z-index:10}.top button,.tools button,.tabs button,.link button{border:1px solid #dce1ec;background:white;border-radius:10px;padding:9px 13px;font-weight:700;cursor:pointer}.top span{font-size:10px;letter-spacing:.12em;color:#7d89a0}main{max-width:1180px;margin:auto;padding:32px 20px 60px}.hero{display:flex;justify-content:space-between;gap:20px;align-items:center;margin-bottom:18px}.hero small{font-weight:900;letter-spacing:.14em;color:#5b59f6}.hero h1{margin:6px 0;font-size:30px}.hero p,.card p{color:#748198;font-size:13px}.save{border:0;background:linear-gradient(135deg,#5b59f6,#7650ef);color:white;border-radius:12px;padding:13px 18px;font-weight:800;cursor:pointer}.card{background:#ffffffdd;border:1px solid #e0e5ef;border-radius:20px;padding:22px;margin:14px 0;box-shadow:0 18px 45px #4b52750c}.card h2{margin:0 0 8px;font-size:18px}.modes{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;margin-top:16px}.modes label{padding:17px;border:1px solid #dfe4ef;border-radius:15px;background:#fbfcff;cursor:pointer}.modes label.active{border-color:#7770f6;background:linear-gradient(135deg,#f0f2ff,#fff8ff)}.modes input{margin-right:8px}.modes strong{font-size:13px}.modes span{display:block;color:#7c879c;font-size:11px;line-height:1.5;margin:8px 0 0 23px}.link{display:flex;gap:8px;align-items:center}.link code{flex:1;overflow:auto;background:#f6f8fc;border:1px solid #e0e4ed;border-radius:10px;padding:12px;font-size:12px}.quick{display:grid;gap:14px;margin-top:15px}.quick>div{padding:14px;border:1px solid #e5e8f0;border-radius:13px;background:#fbfcff}.quick b{display:block;font-size:12px;margin-bottom:8px}.disabled-link{margin:0!important;color:#9aa4b6!important}.url{width:100%;height:44px;border:1px solid #dce1ec;border-radius:10px;padding:0 12px}.tabs{display:flex;justify-content:space-between;align-items:center;gap:15px}.tabs button.sel{background:#efefff;color:#5149d9;border-color:#cbcaff}.card textarea{width:100%;height:460px;resize:vertical;border:1px solid #dce1ec;border-radius:12px;background:#101522;color:#e8edf8;padding:16px;font:12px/1.55 Consolas,monospace}.tools{display:flex;gap:8px;margin-top:10px}.card iframe{width:100%;height:600px;border:1px solid #dce1ec;border-radius:12px;background:white}.alert{padding:11px 14px;border-radius:11px;font-size:12px;margin:10px 0}.err{background:#fff0f1;color:#c53d48}.ok{background:#effdf5;color:#18844a}@media(max-width:760px){.modes{grid-template-columns:1fr}.hero{align-items:flex-start;flex-direction:column}.link{align-items:stretch;flex-wrap:wrap}.link code{flex-basis:100%}.tabs{align-items:flex-start;flex-direction:column}}`}</style></div>
}
